release-essentials:
  when:
    equal: ["essentials", << pipeline.parameters.imageName >> ]
  jobs:
    # ------------------------------------------------------------------------------------
    - job-build-arm64:
        name: base-<< pipeline.parameters.imageTag >>-dev-arm64
        imageName: "essentials"
        imageTag: << pipeline.parameters.imageTag >>
    # ------------------------------------------------------------------------------------
    - job-build-arm64:
        name: base-<< pipeline.parameters.imageTag >>-play-arm64
        imageName: "essentials_play"
        imageTag: << pipeline.parameters.imageTag >>
    # ------------------------------------------------------------------------------------
    - job-build-amd64:
        name: base-<< pipeline.parameters.imageTag >>-dev-amd64
        imageName: "essentials"
        imageTag: << pipeline.parameters.imageTag >>
    # ------------------------------------------------------------------------------------
    - job-build-amd64:
        name: base-<< pipeline.parameters.imageTag >>-play-amd64
        imageName: "essentials_play"
        imageTag: << pipeline.parameters.imageTag >>
    # ------------------------------------------------------------------------------------
    - job-update-manifest:
        name: update-manifest-dev
        imageName: "essentials"
        imageTag: << pipeline.parameters.imageTag >>
        setLatest: false
        requires:
          - base-<< pipeline.parameters.imageTag >>-dev-amd64
          - base-<< pipeline.parameters.imageTag >>-dev-arm64
    # ------------------------------------------------------------------------------------
    - job-update-manifest:
        name: update-manifest-play
        imageName: "essentials_play"
        imageTag: << pipeline.parameters.imageTag >>
        setLatest: false
        requires:
          - base-<< pipeline.parameters.imageTag >>-play-amd64
          - base-<< pipeline.parameters.imageTag >>-play-arm64